SCRIPT_NAME=elf
TEMPLATE_NAME=elf
OUTPUT_FORMAT="elf64-littlebee"
BIG_OUTPUT_FORMAT="elf64-littlebee"
LITTLE_OUTPUT_FORMAT="elf64-bigbee"
TEXT_START_ADDR=0x0
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ARCH=bee
EMBEDDED=yes
unset STACK_ADDR
